use anyhow::{Context, Result, bail};
use serde_json::{Map, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

const CATALOG_RELATIVE_PATH: &str = "rust/crates/proto/catalog/mcp_catalog_v1.json";
const GENERATED_SWIFT_RELATIVE_PATH: &str =
    "Sources/RepoPromptDomainRuntime/MCPDomainGeneratedToolDefinitions.swift";
const REVIEW_RELATIVE_PATH: &str = "docs/spec/mcp-domain-canonical-tool-definitions.generated.json";

pub fn run(repo_root: &Path, check: bool) -> Result<()> {
    let source_path = repo_root.join(CATALOG_RELATIVE_PATH);
    let source_bytes = fs::read(&source_path)
        .with_context(|| format!("read canonical MCP catalog {}", source_path.display()))?;
    let catalog: Value =
        serde_json::from_slice(&source_bytes).context("decode canonical MCP catalog")?;
    validate_catalog(&catalog)?;
    let canonical_json = serde_json::to_vec(&catalog).context("canonicalize MCP catalog")?;
    let digest = hex_digest(&canonical_json);

    let swift = render_swift(&canonical_json, &digest)?;
    let review = render_review(&catalog)?;
    let artifacts = [
        (GENERATED_SWIFT_RELATIVE_PATH, swift),
        (REVIEW_RELATIVE_PATH, review),
    ];
    if check {
        for (relative, expected) in artifacts {
            let path = repo_root.join(relative);
            let actual = fs::read(&path)
                .with_context(|| format!("read generated artifact {}", path.display()))?;
            if actual != expected {
                bail!(
                    "generated MCP catalog artifact is stale: {}",
                    path.display()
                );
            }
        }
        println!("MCP catalog artifacts match (digest {digest})");
    } else {
        for (relative, bytes) in artifacts {
            let path = repo_root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, bytes)?;
        }
        println!("generated MCP catalog artifacts (digest {digest})");
    }
    Ok(())
}

fn validate_catalog(catalog: &Value) -> Result<()> {
    let object = catalog
        .as_object()
        .context("MCP catalog must be an object")?;
    if object.get("catalog_version").and_then(Value::as_u64) != Some(1)
        || object
            .get("definition_schema_version")
            .and_then(Value::as_u64)
            != Some(1)
    {
        bail!("unsupported MCP catalog version");
    }
    let tools = object
        .get("tools")
        .and_then(Value::as_array)
        .context("MCP catalog tools must be an array")?;
    if tools.len() != 27 {
        bail!("MCP catalog must contain 27 tools, found {}", tools.len());
    }
    let mut names = BTreeSet::new();
    for tool in tools {
        let name = tool
            .get("name")
            .and_then(Value::as_str)
            .context("tool name missing")?;
        if name.is_empty() || !names.insert(name.to_owned()) {
            bail!("MCP catalog contains duplicate or empty tool name {name:?}");
        }
        if tool
            .get("input_schema")
            .and_then(Value::as_object)
            .is_none()
        {
            bail!("tool {name} input_schema must be an object");
        }
    }
    Ok(())
}

fn hex_digest(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn render_swift(canonical_json: &[u8], digest: &str) -> Result<Vec<u8>> {
    let json = String::from_utf8(canonical_json.to_vec()).context("MCP catalog is not UTF-8")?;
    if json.contains("\"\"\"#") {
        bail!("MCP catalog contains an unsupported raw-string delimiter");
    }
    // Keep the canonical JSON inspectable in a raw Swift literal; it is not a second authored
    // source and avoids the opaque base64 schema representation retired by P8.
    let source = format!(
        r##"// @generated by xtask mcp-catalog; do not edit.
import Foundation
import MCP

package struct MCPDomainGeneratedToolOperationPolicy: Codable, Hashable, Sendable {{
    package let argumentKey: String
    package let operations: [String]
    package let aliases: [String: String]
    package let defaultOperation: String?
    package let normalization: String

    package enum CodingKeys: String, CodingKey {{
        case argumentKey = "argument_key"
        case operations
        case aliases
        case defaultOperation = "default_operation"
        case normalization
    }}
}}

package struct MCPDomainGeneratedToolLimits: Codable, Hashable, Sendable {{
    package let connectionLane: Int
    package let resourceLease: Int?
    package let resourceScope: String?

    package enum CodingKeys: String, CodingKey {{
        case connectionLane = "connection_lane"
        case resourceLease = "resource_lease"
        case resourceScope = "resource_scope"
    }}
}}

package struct MCPDomainGeneratedToolRecord: Codable, Hashable, Sendable {{
    package let name: String
    package let description: String
    package let inputSchema: Value
    package let annotations: MCPDomainToolAnnotations
    package let enabledByDefault: Bool
    package let scope: String
    package let registrationScopes: [String]
    package let capability: String
    package let admissionClass: String
    package let operationPolicy: MCPDomainGeneratedToolOperationPolicy?
    package let limits: MCPDomainGeneratedToolLimits
    package let sharedRead: Bool

    package enum CodingKeys: String, CodingKey {{
        case name
        case description
        case inputSchema = "input_schema"
        case annotations
        case enabledByDefault = "enabled_by_default"
        case scope
        case registrationScopes = "registration_scopes"
        case capability
        case admissionClass = "admission_class"
        case operationPolicy = "operation_policy"
        case limits
        case sharedRead = "shared_read"
    }}

    package var definition: MCPDomainToolDefinition {{
        MCPDomainToolDefinition(
            name: name,
            description: description,
            inputSchema: inputSchema,
            annotations: annotations,
            isEnabledByDefault: enabledByDefault
        )
    }}
}}

private struct MCPDomainGeneratedCatalogDocument: Codable {{
    let catalogVersion: Int
    let definitionSchemaVersion: Int
    let tools: [MCPDomainGeneratedToolRecord]

    enum CodingKeys: String, CodingKey {{
        case catalogVersion = "catalog_version"
        case definitionSchemaVersion = "definition_schema_version"
        case tools
    }}
}}

package enum MCPDomainGeneratedToolDefinitions {{
    package static let catalogVersion = 1
    package static let definitionSchemaVersion = 1
    package static let catalogDigest = "{digest}"
    package static let records: [MCPDomainGeneratedToolRecord] = decodeDocument()?.tools ?? []
    package static let definitions: [MCPDomainToolDefinition] = records.map(\.definition)

    package static func definition(named name: String) -> MCPDomainToolDefinition? {{
        definitionsByName[name]
    }}

    package static func record(named name: String) -> MCPDomainGeneratedToolRecord? {{
        recordsByName[name]
    }}

    package static func reviewSnapshotData() throws -> Data {{
        struct Provenance: Encodable {{
            let formatVersion: Int
            let authority: String
            let generatedFrom: String
            let regeneration: String
        }}
        struct Snapshot: Encodable {{
            let provenance: Provenance
            let tools: [MCPDomainToolDefinition]
        }}
        let snapshot = Snapshot(
            provenance: Provenance(
                formatVersion: 1,
                authority: "generated-review-projection-only",
                generatedFrom: "rust/crates/proto/catalog/mcp_catalog_v1.json",
                regeneration: "make dev-cargo-codegen && make dev-cargo-codegen-check"
            ),
            tools: definitions
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        var data = try encoder.encode(snapshot)
        data.append(0x0A)
        return data
    }}

    private static let definitionsByName = Dictionary(uniqueKeysWithValues: definitions.map {{ ($0.name, $0) }})
    private static let recordsByName = Dictionary(uniqueKeysWithValues: records.map {{ ($0.name, $0) }})

    private static func decodeDocument() -> MCPDomainGeneratedCatalogDocument? {{
        let data = Data(#"{json}"#.utf8)
        let document: MCPDomainGeneratedCatalogDocument
        do {{
            document = try JSONDecoder().decode(MCPDomainGeneratedCatalogDocument.self, from: data)
        }} catch {{
            return nil
        }}
        guard document.catalogVersion == catalogVersion,
              document.definitionSchemaVersion == definitionSchemaVersion,
              document.tools.count == 27,
              Set(document.tools.map(\.name)).count == document.tools.count
        else {{
            return nil
        }}
        return document
    }}
}}
"##
    );
    Ok(source.into_bytes())
}

fn render_review(catalog: &Value) -> Result<Vec<u8>> {
    let tools = catalog
        .get("tools")
        .and_then(Value::as_array)
        .context("MCP catalog tools missing")?;
    let projected = tools
        .iter()
        .map(|tool| {
            let object = tool.as_object().expect("validated object");
            let mut projection = Map::new();
            projection.insert("name".to_owned(), object["name"].clone());
            projection.insert("description".to_owned(), object["description"].clone());
            projection.insert("inputSchema".to_owned(), object["input_schema"].clone());
            projection.insert("annotations".to_owned(), object["annotations"].clone());
            projection.insert(
                "isEnabledByDefault".to_owned(),
                object["enabled_by_default"].clone(),
            );
            Value::Object(projection)
        })
        .collect::<Vec<_>>();
    let mut provenance = Map::new();
    provenance.insert(
        "authority".to_owned(),
        Value::String("generated-review-projection-only".to_owned()),
    );
    provenance.insert("formatVersion".to_owned(), Value::from(1));
    provenance.insert(
        "generatedFrom".to_owned(),
        Value::String(CATALOG_RELATIVE_PATH.to_owned()),
    );
    provenance.insert(
        "regeneration".to_owned(),
        Value::String("make dev-cargo-codegen && make dev-cargo-codegen-check".to_owned()),
    );
    let mut review = Map::new();
    review.insert("provenance".to_owned(), Value::Object(provenance));
    review.insert("tools".to_owned(), Value::Array(projected));
    let json = serde_json::to_string_pretty(&Value::Object(review))?;
    let mut bytes = swift_pretty_json(json.as_bytes());
    // Swift JSONEncoder renders an empty object across two blank lines in pretty mode.
    let rendered = String::from_utf8(bytes).expect("serde_json output is UTF-8");
    bytes = rendered
        .replace("\"annotations\" : {}", "\"annotations\" : {\n\n      }")
        .into_bytes();
    bytes.push(b'\n');
    Ok(bytes)
}

/// Swift's JSONEncoder pretty printer uses a space on both sides of object colons. Keep the
/// readable projection byte-identical without changing colons embedded in JSON strings.
fn swift_pretty_json(input: &[u8]) -> Vec<u8> {
    let mut output = Vec::with_capacity(input.len() + 256);
    let mut in_string = false;
    let mut escaped = false;
    for (index, &byte) in input.iter().enumerate() {
        if in_string {
            output.push(byte);
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == b'"' {
                in_string = false;
            }
            continue;
        }
        if byte == b'"' {
            in_string = true;
            output.push(byte);
        } else if byte == b':' {
            output.push(b' ');
            output.push(b':');
            if input.get(index + 1) != Some(&b' ') {
                output.push(b' ');
            }
        } else {
            output.push(byte);
        }
    }
    output
}
