//! agent-host-v1 Protobuf code generation (ADR-0009, ADR-0011 P2; design §11 "编解码归属").
//!
//! `protox` compiles `rust/crates/proto/schema/agent_host_v1.proto` in-process -- no system `protoc`
//! is consulted, so the pinned `Cargo.lock` is the whole toolchain (ADR-0007). `prost-build` renders
//! the descriptor set to Rust, and the result is treated like every other generated artifact:
//! written by `xtask generate`, committed, and proven byte-identical by `xtask generate --check`.
//!
//! The rendered module is committed rather than produced by a `build.rs` so that `agentry-proto`
//! builds with plain `cargo build --locked`, the fingerprint in `identity.rs` covers the exact
//! Rust the codec was compiled from, and reviewers see schema changes as Rust diffs.

use anyhow::{Context, Result, bail};
use std::fs;
use std::path::Path;

/// Schema owned by `agentry-proto`.
pub const SCHEMA_PATH: &str = "rust/crates/proto/schema/agent_host_v1.proto";
/// Checked-in prost output, included by `rust/crates/proto/src/agent_host/mod.rs`.
pub const GENERATED_PATH: &str = "rust/crates/proto/src/generated/agent_host_v1.rs";
const PACKAGE: &str = "agentry.agent_host.v1";
const HEADER: &str = "// @generated by `cargo run -p xtask -- generate` (protox + prost-build) from\n// rust/crates/proto/schema/agent_host_v1.proto; do not edit. Frozen at end of P2 -- see the schema\n// header for the compatibility rules.\n";

/// Renders the agent-host-v1 Rust module and returns its bytes (unnormalized).
pub fn generate(repo_root: &Path, stage: &Path) -> Result<Vec<u8>> {
    let schema = repo_root.join(SCHEMA_PATH);
    if !schema.is_file() {
        bail!("agent-host-v1 schema is missing at {SCHEMA_PATH}");
    }
    let include = schema
        .parent()
        .context("agent-host-v1 schema has no parent directory")?;
    let descriptors = protox::compile([schema.as_path()], [include])
        .map_err(|error| anyhow::anyhow!("compile {SCHEMA_PATH}: {error}"))?;

    let out_dir = stage.join("proto");
    if out_dir.exists() {
        fs::remove_dir_all(&out_dir)?;
    }
    fs::create_dir_all(&out_dir)?;
    let mut config = prost_build::Config::new();
    config.out_dir(&out_dir);
    // Deterministic map encoding if a map field is ever added; v1 uses repeated key/value messages.
    config.btree_map(["."]);
    config
        .compile_fds(descriptors)
        .context("render agent-host-v1 Rust with prost-build")?;

    let rendered = fs::read(out_dir.join(format!("{PACKAGE}.rs")))
        .with_context(|| format!("prost-build did not render {PACKAGE}.rs"))?;
    let mut output = HEADER.as_bytes().to_vec();
    output.extend_from_slice(&rendered);
    Ok(output)
}
