//! E-P6-2 Part A: a `posix_spawnp` mirror of `ProcessLauncher.swift`, for spawn-attribute
//! parity measurement against the Swift launcher via `bin/probe.rs`.
//!
//! Ported line-for-line from `Sources/RepoPrompt/Infrastructure/Process/ProcessLauncher.swift`
//! per contract section 5.1, using the `nix` crate's safe wrappers (already pinned at
//! `rust/Cargo.toml:31` `nix = "=0.30.1"`, already feature-flagged for `agentry-runtime` at
//! `rust/crates/runtime/Cargo.toml`). **Zero `unsafe` blocks in this module** -- every
//! `nix::spawn`/`nix::unistd`/`nix::fcntl` call used here is a safe `pub fn`, confirmed by
//! reading the pinned crate source (`~/.cargo/registry/.../nix-0.30.1/src/spawn.rs`), matching
//! contract section 5.2/section 12's verified-coverage claim.
//!
//! **Working-directory (`chdir`) support, closed at P6-7.** `posix_spawn_file_actions_addchdir_np`
//! has no `nix` wrapper in 0.30.1 and is declared in `libc` 0.2.189 only for
//! linux-gnu/linux-musl/cygwin/hurd/solarish -- absent from every Apple target
//! (`libc-0.2.189/src/unix/bsd/apple/mod.rs` has no such symbol; confirmed by direct source read
//! during this spike). P6-4 landed the production hand-declared `extern "C"` binding for this
//! symbol at `rust/crates/runtime/src/agent_claude/process/addchdir.rs`, gated by a scoped
//! `#[allow(unsafe_code)]` exception the production crate's `unsafe_code = "deny"` posture
//! permits. This spike is not subject to that crate's `deny`/guardrail posture (own workspace, own
//! `Cargo.toml`, no `#![forbid(unsafe_code)]` anywhere in this crate -- confirmed by grep), so it
//! carries the identical binding directly rather than depending on `agentry-runtime` (this spike is
//! deliberately isolated from the parent `rust/` workspace, module doc above). E-P6-2 Part A's
//! "with cwd" configuration row, previously a named partial in the P6-2 results doc, is closed by
//! P6-7's `part_a_config_10_with_cwd` (Rust arm) and `testConfig10WithCwd` (Swift arm).
//!
//! **`POSIX_SPAWN_CLOEXEC_DEFAULT` resolved, in the spawner's favor.** Contract section 5.1/section 12
//! named this an open question: whether `nix`'s generated `PosixSpawnFlags` bitflags type exposes a
//! raw-bits constructor that admits the flag without `unsafe`. Confirmed yes: `PosixSpawnFlags` is
//! generated by `nix`'s `libc_bitflags!` macro, which wraps the `bitflags` crate, which always
//! generates a safe `pub const fn from_bits_truncate` (verified: `nix::spawn::PosixSpawnFlags::flags()`
//! itself calls `PosixSpawnFlags::from_bits_truncate` internally at `spawn.rs:86`). Combining
//! `libc::POSIX_SPAWN_CLOEXEC_DEFAULT` (present for Apple targets, `libc-0.2.189/.../apple/mod.rs:3819`)
//! with the `nix`-named flags via `from_bits_truncate` therefore needs no `unsafe` either. This is a
//! narrower, more favorable finding than the contract's own hedge and is recorded in the P6-2 results
//! doc.

use std::ffi::CString;
use std::os::fd::{AsRawFd, OwnedFd};

use nix::fcntl::{fcntl, FcntlArg, FdFlag};
use nix::sys::signal::{SigSet, Signal};
use nix::spawn::{posix_spawnp, PosixSpawnAttr, PosixSpawnFileActions, PosixSpawnFlags};
use nix::unistd::{pipe, Pid};

// Hand-declared `extern "C"` binding for a Darwin libc symbol `nix` 0.30.1 does not wrap and
// `libc` 0.2.189 does not declare on Apple targets (module doc). Identical in shape to the
// production binding at `rust/crates/runtime/src/agent_claude/process/addchdir.rs` -- duplicated
// here rather than shared because this spike is intentionally isolated from the `rust/` workspace
// (own `Cargo.toml`, own `Cargo.lock`, not a dependency of `agentry-runtime`).
unsafe extern "C" {
    fn posix_spawn_file_actions_addchdir_np(
        file_actions: *mut libc::posix_spawn_file_actions_t,
        path: *const libc::c_char,
    ) -> libc::c_int;
}

/// Adds a chdir action to `actions`. Mirrors the production `addchdir::add_chdir`'s pointer-cast
/// approach: `PosixSpawnFileActions` is `#[repr(transparent)]` over `libc::posix_spawn_file_actions_t`
/// (verified by direct source read of the pinned `nix = "=0.30.1"`), so a `*mut PosixSpawnFileActions`
/// and a `*mut libc::posix_spawn_file_actions_t` share address and layout -- the same pattern `nix`'s
/// own `add_dup2`/`add_close` use internally, just from outside the type since its field is private.
fn add_chdir(actions: &mut PosixSpawnFileActions, path: &CString) -> Result<(), i32> {
    debug_assert_eq!(
        std::mem::size_of::<PosixSpawnFileActions>(),
        std::mem::size_of::<libc::posix_spawn_file_actions_t>(),
        "nix::spawn::PosixSpawnFileActions layout assumption no longer holds -- re-verify before proceeding"
    );
    // SAFETY: `actions` is a valid, exclusively-borrowed `PosixSpawnFileActions` for the duration of
    // this call (enforced by the `&mut` borrow), verified `#[repr(transparent)]`-compatible above;
    // `path` is a valid NUL-terminated `CString` reference whose pointer remains valid for the
    // duration of this synchronous call, which does not retain it past return (POSIX).
    let fa_ptr = std::ptr::from_mut(actions).cast::<libc::posix_spawn_file_actions_t>();
    let rc = unsafe { posix_spawn_file_actions_addchdir_np(fa_ptr, path.as_ptr()) };
    if rc == 0 { Ok(()) } else { Err(rc) }
}

#[derive(Debug)]
pub enum SpawnError {
    Pipe(nix::Error),
    CloseOnExec(nix::Error),
    FileActions(&'static str, nix::Error),
    /// `posix_spawn_file_actions_addchdir_np` failed; payload is the raw `errno` value it returned
    /// (this family returns the error code directly rather than setting the global `errno`).
    Chdir(i32),
    Attributes(&'static str, nix::Error),
    Spawn(nix::Error),
    /// Invalid working-directory path (contains an interior NUL).
    InvalidArgument(&'static str),
}

pub struct SpawnConfig<'a> {
    pub command: &'a str,
    pub arguments: &'a [String],
    /// Full replacement environment, exactly as `ProcessLauncher.spawn`'s `environment` parameter
    /// -- **not** merged with the parent's environment.
    pub environment: &'a [(String, String)],
    pub working_directory: Option<&'a str>,
}

#[derive(Debug)]
pub struct SpawnedProcess {
    pub pid: i32,
    pub process_group_id: i32,
    pub stdin_write: OwnedFd,
    pub stdout_read: OwnedFd,
    pub stderr_read: OwnedFd,
}

fn set_cloexec(fd: &OwnedFd) -> Result<(), nix::Error> {
    // `nix::fcntl::fcntl` is a safe `pub fn` generic over `AsFd`; passing `&OwnedFd` avoids any
    // raw-fd borrow, so this needs no `unsafe` block. Mirrors
    // `POSIXDescriptorSupport.setCloseOnExec` (`ProcessLauncher.swift:108-116`).
    fcntl(fd, FcntlArg::F_SETFD(FdFlag::FD_CLOEXEC))?;
    Ok(())
}

/// Mirrors `ProcessLauncher.spawn` (`ProcessLauncher.swift:85-335`) attribute-for-attribute,
/// including the working directory (`addchdir_np`, closed at P6-7 -- see module doc).
pub fn spawn(config: &SpawnConfig) -> Result<SpawnedProcess, SpawnError> {
    // Three pipes, close-on-exec on every fd -- ProcessLauncher.swift:92-156.
    let (stdin_read, stdin_write) = pipe().map_err(SpawnError::Pipe)?;
    let (stdout_read, stdout_write) = pipe().map_err(SpawnError::Pipe)?;
    let (stderr_read, stderr_write) = pipe().map_err(SpawnError::Pipe)?;
    for fd in [
        &stdin_read,
        &stdin_write,
        &stdout_read,
        &stdout_write,
        &stderr_read,
        &stderr_write,
    ] {
        set_cloexec(fd).map_err(SpawnError::CloseOnExec)?;
    }

    // File actions: dup2 into 0/1/2, then close the parent-retained ends inside the child --
    // ProcessLauncher.swift:178-183.
    let mut file_actions = PosixSpawnFileActions::init().map_err(|e| SpawnError::FileActions("init", e))?;
    file_actions
        .add_dup2(stdin_read.as_raw_fd(), libc::STDIN_FILENO)
        .map_err(|e| SpawnError::FileActions("adddup2(stdin)", e))?;
    file_actions
        .add_dup2(stdout_write.as_raw_fd(), libc::STDOUT_FILENO)
        .map_err(|e| SpawnError::FileActions("adddup2(stdout)", e))?;
    file_actions
        .add_dup2(stderr_write.as_raw_fd(), libc::STDERR_FILENO)
        .map_err(|e| SpawnError::FileActions("adddup2(stderr)", e))?;
    file_actions
        .add_close(stdin_write.as_raw_fd())
        .map_err(|e| SpawnError::FileActions("addclose(stdin write)", e))?;
    file_actions
        .add_close(stdout_read.as_raw_fd())
        .map_err(|e| SpawnError::FileActions("addclose(stdout read)", e))?;
    file_actions
        .add_close(stderr_read.as_raw_fd())
        .map_err(|e| SpawnError::FileActions("addclose(stderr read)", e))?;

    // chdir, if requested -- order matches production `agent_claude::process::spawn`: dup2/close
    // before chdir, since chdir only affects the child's subsequent relative-path resolution.
    if let Some(dir) = config.working_directory {
        let dir_c = CString::new(dir).map_err(|_| SpawnError::InvalidArgument("working_directory"))?;
        add_chdir(&mut file_actions, &dir_c).map_err(SpawnError::Chdir)?;
    }

    // Attributes: sigdefault(SIGPIPE), empty sigmask, new pgroup, CLOEXEC_DEFAULT --
    // ProcessLauncher.swift:213-275.
    let mut attr = PosixSpawnAttr::init().map_err(|e| SpawnError::Attributes("init", e))?;

    let mut default_signals = SigSet::empty();
    default_signals.add(Signal::SIGPIPE);
    attr.set_sigdefault(&default_signals)
        .map_err(|e| SpawnError::Attributes("setsigdefault", e))?;

    attr.set_sigmask(&SigSet::empty())
        .map_err(|e| SpawnError::Attributes("setsigmask", e))?;

    attr.set_pgroup(Pid::from_raw(0))
        .map_err(|e| SpawnError::Attributes("setpgroup", e))?;

    let base_flags = PosixSpawnFlags::POSIX_SPAWN_SETSIGDEF
        | PosixSpawnFlags::POSIX_SPAWN_SETSIGMASK
        | PosixSpawnFlags::POSIX_SPAWN_SETPGROUP;
    // See module doc: resolved without `unsafe` via `from_bits_truncate` on the raw libc constant.
    let flags = PosixSpawnFlags::from_bits_truncate(base_flags.bits() | libc::POSIX_SPAWN_CLOEXEC_DEFAULT);
    attr.set_flags(flags)
        .map_err(|e| SpawnError::Attributes("setflags", e))?;

    let command_c = CString::new(config.command).map_err(|_| SpawnError::Spawn(nix::Error::EINVAL))?;
    let mut argv_c: Vec<CString> = Vec::with_capacity(config.arguments.len() + 1);
    argv_c.push(command_c.clone());
    for arg in config.arguments {
        argv_c.push(CString::new(arg.as_str()).map_err(|_| SpawnError::Spawn(nix::Error::EINVAL))?);
    }
    let envp_c: Vec<CString> = config
        .environment
        .iter()
        .map(|(k, v)| CString::new(format!("{k}={v}")).map_err(|_| SpawnError::Spawn(nix::Error::EINVAL)))
        .collect::<Result<_, _>>()?;

    let pid = posix_spawnp(&command_c, &file_actions, &attr, &argv_c, &envp_c).map_err(SpawnError::Spawn)?;

    // Parent-retained ends of the pipe halves handed to the child are closed by the spawned
    // process's own file actions above; the parent still holds the *other* halves and must close
    // its copies of the child-facing halves here, exactly as ProcessLauncher.swift:319-321.
    drop(stdin_read);
    drop(stdout_write);
    drop(stderr_write);

    Ok(SpawnedProcess {
        pid: pid.as_raw(),
        process_group_id: pid.as_raw(),
        stdin_write,
        stdout_read,
        stderr_read,
    })
}
