//! E-P6-2 Part A: a `posix_spawnp` mirror of `ProcessLauncher.swift`, for spawn-attribute
//! parity measurement against the Swift launcher via `bin/probe.rs`.
//!
//! Ported line-for-line from `Sources/RepoPrompt/Infrastructure/Process/ProcessLauncher.swift`
//! per contract section 5.1, using the `nix` crate's safe wrappers (already pinned at
//! `rust/Cargo.toml:31` `nix = "=0.30.1"`, already feature-flagged for `agentry-runtime` at
//! `rust/crates/runtime/Cargo.toml`). **Zero `unsafe` blocks in this module** -- every
//! `nix::spawn`/`nix::unistd`/`nix::fcntl` call used here is a safe `pub fn`, confirmed by
//! reading the pinned crate source (`~/.cargo/registry/.../nix-0.30.1/src/spawn.rs`), matching
//! contract section 5.2/section 12's verified-coverage claim.
//!
//! **Confirmed, not attempted: working-directory (`chdir`) support.** `posix_spawn_file_actions_addchdir_np`
//! has no `nix` wrapper in 0.30.1 and is declared in `libc` 0.2.189 only for
//! linux-gnu/linux-musl/cygwin/hurd/solarish -- absent from every Apple target
//! (`libc-0.2.189/src/unix/bsd/apple/mod.rs` has no such symbol; confirmed by direct source read
//! during this spike). Per this task's binding carry-forward ("addchdir_np extern is a P6-4, not
//! P6-2, prerequisite"), this spawner intentionally does **not** implement `chdir` and returns
//! [`SpawnError::WorkingDirectoryUnsupported`] if asked to. E-P6-2 Part A's "with cwd" configuration
//! row is consequently a named partial in the P6-2 results doc, not a landed `unsafe_code`
//! exception taken early to force it green.
//!
//! **`POSIX_SPAWN_CLOEXEC_DEFAULT` resolved, in the spawner's favor.** Contract section 5.1/section 12
//! named this an open question: whether `nix`'s generated `PosixSpawnFlags` bitflags type exposes a
//! raw-bits constructor that admits the flag without `unsafe`. Confirmed yes: `PosixSpawnFlags` is
//! generated by `nix`'s `libc_bitflags!` macro, which wraps the `bitflags` crate, which always
//! generates a safe `pub const fn from_bits_truncate` (verified: `nix::spawn::PosixSpawnFlags::flags()`
//! itself calls `PosixSpawnFlags::from_bits_truncate` internally at `spawn.rs:86`). Combining
//! `libc::POSIX_SPAWN_CLOEXEC_DEFAULT` (present for Apple targets, `libc-0.2.189/.../apple/mod.rs:3819`)
//! with the `nix`-named flags via `from_bits_truncate` therefore needs no `unsafe` either. This is a
//! narrower, more favorable finding than the contract's own hedge and is recorded in the P6-2 results
//! doc.

use std::ffi::CString;
use std::os::fd::{AsRawFd, OwnedFd};

use nix::fcntl::{fcntl, FcntlArg, FdFlag};
use nix::sys::signal::{SigSet, Signal};
use nix::spawn::{posix_spawnp, PosixSpawnAttr, PosixSpawnFileActions, PosixSpawnFlags};
use nix::unistd::{pipe, Pid};

#[derive(Debug)]
pub enum SpawnError {
    Pipe(nix::Error),
    CloseOnExec(nix::Error),
    FileActions(&'static str, nix::Error),
    Attributes(&'static str, nix::Error),
    Spawn(nix::Error),
    /// Confirmed P6-4 prerequisite: `posix_spawn_file_actions_addchdir_np` has no safe `nix`
    /// wrapper and no `libc` declaration on Apple targets. Not attempted in this spike.
    WorkingDirectoryUnsupported,
}

pub struct SpawnConfig<'a> {
    pub command: &'a str,
    pub arguments: &'a [String],
    /// Full replacement environment, exactly as `ProcessLauncher.spawn`'s `environment` parameter
    /// -- **not** merged with the parent's environment.
    pub environment: &'a [(String, String)],
    pub working_directory: Option<&'a str>,
}

#[derive(Debug)]
pub struct SpawnedProcess {
    pub pid: i32,
    pub process_group_id: i32,
    pub stdin_write: OwnedFd,
    pub stdout_read: OwnedFd,
    pub stderr_read: OwnedFd,
}

fn set_cloexec(fd: &OwnedFd) -> Result<(), nix::Error> {
    // `nix::fcntl::fcntl` is a safe `pub fn` generic over `AsFd`; passing `&OwnedFd` avoids any
    // raw-fd borrow, so this needs no `unsafe` block. Mirrors
    // `POSIXDescriptorSupport.setCloseOnExec` (`ProcessLauncher.swift:108-116`).
    fcntl(fd, FcntlArg::F_SETFD(FdFlag::FD_CLOEXEC))?;
    Ok(())
}

/// Mirrors `ProcessLauncher.spawn` (`ProcessLauncher.swift:85-335`) attribute-for-attribute, minus
/// `chdir` (see module doc). Returns [`SpawnError::WorkingDirectoryUnsupported`] rather than
/// silently ignoring a requested working directory.
pub fn spawn(config: &SpawnConfig) -> Result<SpawnedProcess, SpawnError> {
    if config.working_directory.is_some() {
        return Err(SpawnError::WorkingDirectoryUnsupported);
    }

    // Three pipes, close-on-exec on every fd -- ProcessLauncher.swift:92-156.
    let (stdin_read, stdin_write) = pipe().map_err(SpawnError::Pipe)?;
    let (stdout_read, stdout_write) = pipe().map_err(SpawnError::Pipe)?;
    let (stderr_read, stderr_write) = pipe().map_err(SpawnError::Pipe)?;
    for fd in [
        &stdin_read,
        &stdin_write,
        &stdout_read,
        &stdout_write,
        &stderr_read,
        &stderr_write,
    ] {
        set_cloexec(fd).map_err(SpawnError::CloseOnExec)?;
    }

    // File actions: dup2 into 0/1/2, then close the parent-retained ends inside the child --
    // ProcessLauncher.swift:178-183.
    let mut file_actions = PosixSpawnFileActions::init().map_err(|e| SpawnError::FileActions("init", e))?;
    file_actions
        .add_dup2(stdin_read.as_raw_fd(), libc::STDIN_FILENO)
        .map_err(|e| SpawnError::FileActions("adddup2(stdin)", e))?;
    file_actions
        .add_dup2(stdout_write.as_raw_fd(), libc::STDOUT_FILENO)
        .map_err(|e| SpawnError::FileActions("adddup2(stdout)", e))?;
    file_actions
        .add_dup2(stderr_write.as_raw_fd(), libc::STDERR_FILENO)
        .map_err(|e| SpawnError::FileActions("adddup2(stderr)", e))?;
    file_actions
        .add_close(stdin_write.as_raw_fd())
        .map_err(|e| SpawnError::FileActions("addclose(stdin write)", e))?;
    file_actions
        .add_close(stdout_read.as_raw_fd())
        .map_err(|e| SpawnError::FileActions("addclose(stdout read)", e))?;
    file_actions
        .add_close(stderr_read.as_raw_fd())
        .map_err(|e| SpawnError::FileActions("addclose(stderr read)", e))?;

    // Attributes: sigdefault(SIGPIPE), empty sigmask, new pgroup, CLOEXEC_DEFAULT --
    // ProcessLauncher.swift:213-275.
    let mut attr = PosixSpawnAttr::init().map_err(|e| SpawnError::Attributes("init", e))?;

    let mut default_signals = SigSet::empty();
    default_signals.add(Signal::SIGPIPE);
    attr.set_sigdefault(&default_signals)
        .map_err(|e| SpawnError::Attributes("setsigdefault", e))?;

    attr.set_sigmask(&SigSet::empty())
        .map_err(|e| SpawnError::Attributes("setsigmask", e))?;

    attr.set_pgroup(Pid::from_raw(0))
        .map_err(|e| SpawnError::Attributes("setpgroup", e))?;

    let base_flags = PosixSpawnFlags::POSIX_SPAWN_SETSIGDEF
        | PosixSpawnFlags::POSIX_SPAWN_SETSIGMASK
        | PosixSpawnFlags::POSIX_SPAWN_SETPGROUP;
    // See module doc: resolved without `unsafe` via `from_bits_truncate` on the raw libc constant.
    let flags = PosixSpawnFlags::from_bits_truncate(base_flags.bits() | libc::POSIX_SPAWN_CLOEXEC_DEFAULT);
    attr.set_flags(flags)
        .map_err(|e| SpawnError::Attributes("setflags", e))?;

    let command_c = CString::new(config.command).map_err(|_| SpawnError::Spawn(nix::Error::EINVAL))?;
    let mut argv_c: Vec<CString> = Vec::with_capacity(config.arguments.len() + 1);
    argv_c.push(command_c.clone());
    for arg in config.arguments {
        argv_c.push(CString::new(arg.as_str()).map_err(|_| SpawnError::Spawn(nix::Error::EINVAL))?);
    }
    let envp_c: Vec<CString> = config
        .environment
        .iter()
        .map(|(k, v)| CString::new(format!("{k}={v}")).map_err(|_| SpawnError::Spawn(nix::Error::EINVAL)))
        .collect::<Result<_, _>>()?;

    let pid = posix_spawnp(&command_c, &file_actions, &attr, &argv_c, &envp_c).map_err(SpawnError::Spawn)?;

    // Parent-retained ends of the pipe halves handed to the child are closed by the spawned
    // process's own file actions above; the parent still holds the *other* halves and must close
    // its copies of the child-facing halves here, exactly as ProcessLauncher.swift:319-321.
    drop(stdin_read);
    drop(stdout_write);
    drop(stderr_write);

    Ok(SpawnedProcess {
        pid: pid.as_raw(),
        process_group_id: pid.as_raw(),
        stdin_write,
        stdout_read,
        stderr_read,
    })
}
